name: Automated PR Quality Checks

on:
  pull_request:
    branches:
      - '**'
  pull_request_target:
    types: [labeled]
  issue_comment:
    types: [created]

jobs:
  quality-checks:
    name: Code Quality Validation
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'pull_request_target' && github.event.label.name == 'check') ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, 'recheck'))
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.pull_request.head.ref }}
      
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install required tools
        run: |
          python -m pip install --upgrade pip
          pip install black ast
      
      - name: Validate code formatting
        run: |
          echo "Running Black formatter check..."
          black --check --diff .
      
      - name: Verify Python 3.12 syntax compatibility
        run: |
          echo "Checking Python 3.12 syntax compatibility..."
          python -c "
          import ast
          import glob
          import sys
          
          failed = False
          for file in glob.glob('**/*.py', recursive=True):
              try:
                  with open(file, 'r', encoding='utf-8') as f:
                      ast.parse(f.read(), filename=file)
                  print(f'✓ {file}')
              except SyntaxError as e:
                  print(f'✗ {file}: {e}')
                  failed = True
          
          if failed:
              sys.exit(1)
          else:
              print('All Python files have valid syntax for Python 3.12')
          "

  auto-trigger-info:
    name: Workflow Trigger Information
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Display trigger options
        run: |
          echo "This workflow runs automatically on PRs"
          echo "To manually re-trigger:"
          echo "- Add 'check' label to the PR"
          echo "- Comment 'recheck' on the PR"