name: Auto-Merge & YAML Lint

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ".github/workflows/*"
          config_file: ".yamllint.yml"

  auto-merge:
    needs: yaml-lint
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'merge'))
      || (github.event_name == 'issue_comment' && github.event.comment.body == 'merge' && github.event.issue.pull_request)
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
