name: PR Quality Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [labeled]
  issue_comment:
    types: [created]

jobs:
  should-run:
    runs-on: ubuntu-latest
    outputs:
      run-checks: ${{ steps.check.outputs.run-checks }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "run-checks=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request_target" && "${{ github.event.label.name }}" == "check" ]]; then
            echo "run-checks=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "issue_comment" && "${{ github.event.issue.pull_request }}" && "${{ contains(github.event.comment.body, 'recheck') }}" ]]; then
            echo "run-checks=true" >> $GITHUB_OUTPUT
          else
            echo "run-checks=false" >> $GITHUB_OUTPUT
          fi

  code-formatting:
    needs: should-run
    if: needs.should-run.outputs.run-checks == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install black
      - run: black --check --diff .

  python-compatibility:
    needs: should-run
    if: needs.should-run.outputs.run-checks == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          find . -name "*.py" -not -path "./.*" | xargs python -m py_compile

  quality-checks:
    needs: [should-run, code-formatting, python-compatibility]
    if: always() && needs.should-run.outputs.run-checks == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "${{ needs.code-formatting.result }}" == "success" && "${{ needs.python-compatibility.result }}" == "success" ]]; then
            exit 0
          else
            exit 1
          fi