name: PR Quality Checks

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'check')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install black
      - run: black --check .
      - run: python -m compileall -q .
