name: Pull Request Validation

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  issue_comment:
    types: [created]

jobs:
  # Runs when PR has the "check" label
  pr-checks:
    if: contains(github.event.pull_request.labels.*.name, 'check')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install black
      - run: black --check .
      - run: python -m compileall -q .

  # Runs when someone comments "recheck" on a PR
  comment-recheck:
    if: github.event.issue.pull_request && contains(github.event.comment.body || '', 'recheck')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install black
      - run: black --check .
      - run: python -m compileall -q .
